language: rust

matrix:
  include:
    - rust: nightly
      script:
        - cargo test
        - cargo build --tests --features no-panic --release
    - rust: beta
      script:
        - cargo test
    - rust: stable
      script:
        - cargo test
    - rust: 1.15.0
      script:
        - cargo build
        - cargo build --features small
    - name: Miri
      install:
        - MIRI_NIGHTLY=nightly-$(curl -s https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/miri)
        - echo "Installing latest nightly with Miri: $MIRI_NIGHTLY"
        - rustup set profile minimal
        - rustup default "$MIRI_NIGHTLY"
        - rustup component add miri
        - cargo miri setup
      script:
        - cargo miri test
