[package]
name = "ryu"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
build = "build.rs"
publish = false

[dependencies]
no-panic = { version = "0.1", optional = true }

[dev-dependencies]
rand = "0.5"
