[package]
name = "ryu"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
publish = false

[features]
pretty = []

[dependencies]
no-panic = { version = "0.1", optional = true }

[dev-dependencies]
rand = "0.5"

[package.metadata.docs.rs]
features = ["pretty"]

[package.metadata.playground]
features = ["pretty"]
